spring.application.name=SmartAttendance
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_attendance
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=ThisIsMyVerySecureSecretKeyForSmartAttendanceProject2026
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG